import test from 'node:test';
import assert from 'node:assert/strict';
import {createSelfServiceTrial} from '../lib/self_service_trial.mjs';
const origin='https://astro-event-horizon.vercel.app';
function fixture(){
 const data=new Map(),keys=new Set(),verification=[],mail=[];let now=Date.parse('2026-10-02T20:00:00Z');
 const redis={get:async k=>data.get(k)??null,set:async(k,v,o)=>{if(o?.nx&&data.has(k))return null;data.set(k,v);return 'OK';},sadd:async(k,v)=>keys.add(v),eval:async(s,[k])=>{let n=(data.get(k)||0)+1;data.set(k,n);return n;}};
 const deps={redis,sendVerification:async r=>verification.push(r),sendTrial:async r=>mail.push(r),clock:()=>now,getSecret:()=> 'synthetic-fixture-secret',enabled:()=>true};
 async function call(body,headers={origin}){const res={code:200,setHeader(){},status(c){this.code=c;return this;},json(b){this.body=b;return this;}};await createSelfServiceTrial(deps)({method:'POST',headers,body,socket:{remoteAddress:'127.0.0.1'}},res);return res;}
 const request={action:'request',email:'tester@example.invalid',use_case:'Building a market screener',consent:true};
 const verify=()=>({action:'verify',email:request.email,code:verification.at(-1).code});
 return {data,keys,verification,mail,deps,call,request,verify,advance:n=>now+=n};
}
test('disabled deployment and cross-origin calls cannot send mail',async()=>{const f=fixture();f.deps.enabled=()=>false;assert.equal((await f.call(f.request)).code,503);f.deps.enabled=()=>true;assert.equal((await f.call(f.request,{})).code,403);assert.equal(f.verification.length,0);});
test('request sends only verification, persists hash not code, grants nothing',async()=>{const f=fixture();const r=await f.call(f.request);assert.equal(r.code,200);assert.equal(f.keys.size,0);const stored=[...f.data.entries()].find(([k])=>k.startsWith('signup:proof:'))[1];assert.ok(!stored.includes(f.verification[0].code));assert.ok(!JSON.stringify(r.body).includes(f.verification[0].code));});
test('verified activation and concurrent retries create one fixed trial and no key in responses',async()=>{const f=fixture();await f.call(f.request);const results=await Promise.all([f.call(f.verify()),f.call(f.verify())]);assert.ok(results.every(r=>r.code===200));assert.equal(f.keys.size,1);const key=[...f.keys][0];assert.ok(results.every(r=>!JSON.stringify(r.body).includes(key)));assert.equal(Date.parse(f.mail[0].expires_at)-Date.parse(f.mail[0].issued_at),30*86400000);});
test('invalid, wrong-email and expired proofs create no access',async()=>{const f=fixture();await f.call(f.request);assert.equal((await f.call({...f.verify(),code:'bad'})).code,400);assert.equal((await f.call({...f.verify(),email:'other@example.invalid'})).code,400);f.advance(600000);assert.equal((await f.call(f.verify())).code,400);assert.equal(f.keys.size,0);});
test('mail requests and verification attempts are capped',async()=>{const f=fixture();for(let i=0;i<3;i++)assert.equal((await f.call(f.request)).code,200);assert.equal((await f.call(f.request)).code,429);for(let i=0;i<5;i++)await f.call({...f.verify(),code:'99999999'});assert.equal((await f.call(f.verify())).code,429);});
test('SMTP failure retries same key and never changes deadline',async()=>{const f=fixture();await f.call(f.request);f.deps.sendTrial=async()=>{throw Error('fixture');};assert.equal((await f.call(f.verify())).code,503);const key=[...f.keys][0];f.advance(1000);f.deps.sendTrial=async r=>f.mail.push(r);assert.equal((await f.call(f.verify())).code,200);assert.equal(f.mail[0].key,key);});
test('revoked prior trial cannot be revived via public signup',async()=>{const f=fixture();await f.call(f.request);await f.call(f.verify());const path=[...f.data.keys()].find(k=>k.startsWith('trial:'));const record=JSON.parse(f.data.get(path));record.revoked=true;f.data.set(path,JSON.stringify(record));assert.equal((await f.call(f.verify())).code,409);assert.equal(f.keys.size,1);});
test('existing paid and founder keys are not overwritten',async()=>{const f=fixture();f.data.set('key:paid',JSON.stringify({active:true,entitlement:{kind:'founding_supporter'}}));await f.call(f.request);await f.call(f.verify());assert.equal(f.data.get('key:paid'),JSON.stringify({active:true,entitlement:{kind:'founding_supporter'}}));});
test('recipient lists, address comments and header injection are rejected before email',async()=>{const f=fixture();for(const email of ['a,b@example.invalid','a(comment)@example.invalid','a@example.invalid\r\nBcc:other@example.invalid'])assert.equal((await f.call({...f.request,email})).code,400);assert.equal(f.verification.length,0);});
test('a new verified signup cannot renew an expired trial',async()=>{const f=fixture();await f.call(f.request);await f.call(f.verify());f.advance(30*86400000);await f.call(f.request);const r=await f.call(f.verify());assert.equal(r.code,409);assert.equal(r.body.state,'expired');assert.equal(f.keys.size,1);});
test('daily cap protects transactional email capacity',async()=>{const f=fixture();f.data.set('signup:daily',100);assert.equal((await f.call(f.request)).code,429);assert.equal(f.verification.length,0);assert.equal(f.keys.size,0);});
