import Head from 'next/head';
import DataAttribution from '../components/DataAttribution';
export default function MCP(){return <><Head><title>ASTRO MCP — Crypto intelligence for AI tools</title><meta name="description" content="Read ASTRO signal, context and basket intelligence through a free MCP connector."/></Head><main>
<a href="/">← ASTRO</a><h1>ASTRO in your AI workflow.</h1><p>A free, read-only MCP connector for ASTRO's live crypto intelligence. Use it with a client that supports local stdio MCP servers.</p>
<p>The connector preserves all fields returned by signal, context and basket: components, weights, prediction-market assessments, funding, rankings, volatility, strategy gates, confidence and explanations. It does not place trades or expose private orders, positions or balances. Missing data and freshness limitations remain visible.</p>
<h2>Start privately</h2><ol><li><a href="/trial">Activate a free 30-day trial</a>, or use your existing paid or Founding Supporter key.</li><li>Download the <a href="/downloads/astro-intelligence-mcp-0.3.0.zip">connector source package</a>, extract it, and follow its README to install in a private Python environment (Python 3.10+).</li><li>Run <code>astro-mcp configure</code> locally. Paste the emailed key into its hidden prompt—not into an AI chat. A supported native OS credential store is required.</li><li>Configure your MCP client's command as the installed <code>astro-mcp</code> executable and its arguments as <code>["serve"]</code>. Use the full executable path when needed. No key goes in the client JSON.</li></ol>
<h2>Available tools</h2><ul><li><code>astro_get_started</code> — public signup and setup instructions.</li><li><code>astro_signal</code> — composite and component readings.</li><li><code>astro_context</code> — expanded market intelligence and explanations.</li><li><code>astro_basket</code> — the asset basket and decision-support analysis.</li></ul>
<p>One request per resource per 15 minutes per key; the connector reuses recent responses. Reconnecting does not reset that limit. Always inspect source timestamps and stale flags. Individual scores may include fallbacks; availability is not proof of predictive accuracy.</p>
<p>No automatic billing or renewal. The trial starts at email-verified activation and lasts 30 days. The connector remains free; continued API access needs a qualifying entitlement. This is not a hosted OAuth MCP endpoint or an automatic marketplace listing.</p>
<DataAttribution/><a className="badge" href="/"><img src="/jarvis-emblem.jpg" alt="" width="24" height="24"/> RAN BY JARVIS</a>
</main><style jsx>{`main{max-width:850px;margin:32px auto;padding:24px;font:17px/1.7 system-ui;background:#101827;color:#e5edf5;border-radius:16px}a{color:#71e3f5}code{overflow-wrap:anywhere}li{margin-bottom:14px}.badge{display:flex;align-items:center;gap:8px;position:fixed;bottom:12px;right:12px;padding:8px 14px;border-radius:24px;background:#122638cc;backdrop-filter:blur(10px);opacity:.7;font-size:11px}.badge:hover{opacity:1}`}</style></>}
