import Head from 'next/head';
import DataAttribution from '../components/DataAttribution';
export default function MCP(){return <><Head><title>ASTRO MCP — Crypto intelligence for AI tools</title><meta name="description" content="Read ASTRO signal, context and basket intelligence through a free MCP connector."/></Head><main>
<a href="/">← ASTRO</a><h1>ASTRO in your AI workflow.</h1><p>A free, read-only MCP connector for ASTRO's live crypto intelligence. Use it with a client that supports local stdio MCP servers.</p>
<p>The connector preserves all fields returned by signal, context and basket: components, weights, prediction-market assessments, funding, rankings, volatility, strategy gates, confidence and explanations. It does not place trades or expose private orders, positions or balances. Missing data and freshness limitations remain visible.</p>
<h2>Try first. Sign up later.</h2><ol><li>Download the <a href="/downloads/astro-intelligence-mcp-0.4.0.zip">connector source package</a>, extract it, and install in a private Python environment (Python 3.10+).</li><li>Connect your MCP client: command is the full path to the installed <code>astro-mcp</code> executable; arguments are <code>["serve"]</code>, using stdio.</li><li>On your first intelligence request, the connector activates a 30-day anonymous trial and stores its credentials privately in your native OS credential store. No email, card or pasted key required. First access may take about one minute to synchronize; an activating response tells you when to retry.</li><li>At expiry, the tool provides a <a href="/trial">signup link</a>. Enter your newly issued key only through <code>astro-mcp configure</code> locally, then restart the connector. Your tool names and integration stay the same.</li></ol><p>Already a customer? Run <code>astro-mcp configure</code> with your existing key first. It takes precedence and no anonymous trial is issued. Windows Credential Manager, macOS Keychain or Linux Secret Service is required; no plaintext fallback.</p><p>By starting an intelligence request you initiate the trial under our <a href="/terms">terms</a> and <a href="/privacy">privacy notice</a>. The pilot allows 3 installations per network over 30 days, 25 new grants per day globally, and 250 total. Shared networks may hit the cap. <a href="/trial">Verified-email trials</a> remain available. Reinstalling does not renew a saved trial; deleting its credentials may lose access.</p>
<h2>Available tools</h2><ul><li><code>astro_get_started</code> — public signup and setup instructions.</li><li><code>astro_signal</code> — composite and component readings.</li><li><code>astro_context</code> — expanded market intelligence and explanations.</li><li><code>astro_basket</code> — the asset basket and decision-support analysis.</li></ul>
<p>One request per resource per 15 minutes per key; the connector reuses recent responses. Reconnecting does not reset that limit. Always inspect source timestamps and stale flags. Individual scores may include fallbacks; availability is not proof of predictive accuracy.</p>
<p>No automatic billing or renewal. The anonymous trial starts on first automatic activation and lasts 30 consecutive days. Every successful trial response includes its expiry date; expired trials return signup guidance instead of cached data. The connector remains free; continued API access needs a qualifying entitlement. This is not a hosted OAuth MCP endpoint or an automatic marketplace listing.</p>
<DataAttribution/><a className="badge" href="/"><img src="/jarvis-emblem.jpg" alt="" width="24" height="24"/> RAN BY JARVIS</a>
</main><style jsx>{`main{max-width:850px;margin:32px auto;padding:24px;font:17px/1.7 system-ui;background:#101827;color:#e5edf5;border-radius:16px}a{color:#71e3f5}code{overflow-wrap:anywhere}li{margin-bottom:14px}.badge{display:flex;align-items:center;gap:8px;position:fixed;bottom:12px;right:12px;padding:8px 14px;border-radius:24px;background:#122638cc;backdrop-filter:blur(10px);opacity:.7;font-size:11px}.badge:hover{opacity:1}`}</style></>}
